// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_xp_init_game
SEXP cpp_xp_init_game();
RcppExport SEXP _ply_cpp_xp_init_game() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_xp_init_game());
    return rcpp_result_gen;
END_RCPP
}
// cpp_xp_parse_fen
SEXP cpp_xp_parse_fen(std::string fen);
RcppExport SEXP _ply_cpp_xp_parse_fen(SEXP fenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fen(fenSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_xp_parse_fen(fen));
    return rcpp_result_gen;
END_RCPP
}
// cpp_xp_state_to_fen
std::string cpp_xp_state_to_fen(SEXP state);
RcppExport SEXP _ply_cpp_xp_state_to_fen(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_xp_state_to_fen(state));
    return rcpp_result_gen;
END_RCPP
}
// cpp_xp_in_check
bool cpp_xp_in_check(SEXP state, int color);
RcppExport SEXP _ply_cpp_xp_in_check(SEXP stateSEXP, SEXP colorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type state(stateSEXP);
    Rcpp::traits::input_parameter< int >::type color(colorSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_xp_in_check(state, color));
    return rcpp_result_gen;
END_RCPP
}
// cpp_xp_is_legal_ply
bool cpp_xp_is_legal_ply(SEXP state, int ply);
RcppExport SEXP _ply_cpp_xp_is_legal_ply(SEXP stateSEXP, SEXP plySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type state(stateSEXP);
    Rcpp::traits::input_parameter< int >::type ply(plySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_xp_is_legal_ply(state, ply));
    return rcpp_result_gen;
END_RCPP
}
// cpp_xp_apply_ply
SEXP cpp_xp_apply_ply(SEXP state, int ply);
RcppExport SEXP _ply_cpp_xp_apply_ply(SEXP stateSEXP, SEXP plySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type state(stateSEXP);
    Rcpp::traits::input_parameter< int >::type ply(plySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_xp_apply_ply(state, ply));
    return rcpp_result_gen;
END_RCPP
}
// cpp_xp_generate_legal_moves
IntegerVector cpp_xp_generate_legal_moves(SEXP state);
RcppExport SEXP _ply_cpp_xp_generate_legal_moves(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_xp_generate_legal_moves(state));
    return rcpp_result_gen;
END_RCPP
}
// cpp_xp_count_legal_moves
int cpp_xp_count_legal_moves(SEXP state);
RcppExport SEXP _ply_cpp_xp_count_legal_moves(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_xp_count_legal_moves(state));
    return rcpp_result_gen;
END_RCPP
}
// cpp_xp_is_insufficient_material
bool cpp_xp_is_insufficient_material(SEXP state);
RcppExport SEXP _ply_cpp_xp_is_insufficient_material(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_xp_is_insufficient_material(state));
    return rcpp_result_gen;
END_RCPP
}
// cpp_xp_validate_position
bool cpp_xp_validate_position(SEXP state);
RcppExport SEXP _ply_cpp_xp_validate_position(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_xp_validate_position(state));
    return rcpp_result_gen;
END_RCPP
}
// cpp_xp_position_hash
std::string cpp_xp_position_hash(SEXP state);
RcppExport SEXP _ply_cpp_xp_position_hash(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_xp_position_hash(state));
    return rcpp_result_gen;
END_RCPP
}
// cpp_xp_perft
double cpp_xp_perft(std::string fen, int depth);
RcppExport SEXP _ply_cpp_xp_perft(SEXP fenSEXP, SEXP depthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fen(fenSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_xp_perft(fen, depth));
    return rcpp_result_gen;
END_RCPP
}
// cpp_init_game
List cpp_init_game();
RcppExport SEXP _ply_cpp_init_game() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_init_game());
    return rcpp_result_gen;
END_RCPP
}
// cpp_parse_fen
List cpp_parse_fen(std::string fen);
RcppExport SEXP _ply_cpp_parse_fen(SEXP fenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fen(fenSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_parse_fen(fen));
    return rcpp_result_gen;
END_RCPP
}
// cpp_state_to_fen
std::string cpp_state_to_fen(List state);
RcppExport SEXP _ply_cpp_state_to_fen(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_state_to_fen(state));
    return rcpp_result_gen;
END_RCPP
}
// cpp_in_check
bool cpp_in_check(List state, int color);
RcppExport SEXP _ply_cpp_in_check(SEXP stateSEXP, SEXP colorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type state(stateSEXP);
    Rcpp::traits::input_parameter< int >::type color(colorSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_in_check(state, color));
    return rcpp_result_gen;
END_RCPP
}
// cpp_is_legal_ply
bool cpp_is_legal_ply(List state, int ply);
RcppExport SEXP _ply_cpp_is_legal_ply(SEXP stateSEXP, SEXP plySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type state(stateSEXP);
    Rcpp::traits::input_parameter< int >::type ply(plySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_is_legal_ply(state, ply));
    return rcpp_result_gen;
END_RCPP
}
// cpp_apply_ply
List cpp_apply_ply(List state, int ply);
RcppExport SEXP _ply_cpp_apply_ply(SEXP stateSEXP, SEXP plySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type state(stateSEXP);
    Rcpp::traits::input_parameter< int >::type ply(plySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_apply_ply(state, ply));
    return rcpp_result_gen;
END_RCPP
}
// cpp_generate_legal_moves
IntegerVector cpp_generate_legal_moves(List state);
RcppExport SEXP _ply_cpp_generate_legal_moves(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_generate_legal_moves(state));
    return rcpp_result_gen;
END_RCPP
}
// cpp_has_any_legal_ply_with_check
List cpp_has_any_legal_ply_with_check(List state);
RcppExport SEXP _ply_cpp_has_any_legal_ply_with_check(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_has_any_legal_ply_with_check(state));
    return rcpp_result_gen;
END_RCPP
}
// cpp_is_insufficient_material
bool cpp_is_insufficient_material(List state);
RcppExport SEXP _ply_cpp_is_insufficient_material(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_is_insufficient_material(state));
    return rcpp_result_gen;
END_RCPP
}
// cpp_validate_position
bool cpp_validate_position(List state);
RcppExport SEXP _ply_cpp_validate_position(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_validate_position(state));
    return rcpp_result_gen;
END_RCPP
}
// cpp_uci_to_ply
int cpp_uci_to_ply(List state, std::string uci);
RcppExport SEXP _ply_cpp_uci_to_ply(SEXP stateSEXP, SEXP uciSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type state(stateSEXP);
    Rcpp::traits::input_parameter< std::string >::type uci(uciSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_uci_to_ply(state, uci));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ply_to_uci
std::string cpp_ply_to_uci(int ply);
RcppExport SEXP _ply_cpp_ply_to_uci(SEXP plySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type ply(plySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ply_to_uci(ply));
    return rcpp_result_gen;
END_RCPP
}
// cpp_position_hash
std::string cpp_position_hash(List state);
RcppExport SEXP _ply_cpp_position_hash(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_position_hash(state));
    return rcpp_result_gen;
END_RCPP
}
// cpp_enrich_batch
DataFrame cpp_enrich_batch(CharacterVector fens, CharacterVector uci_moves);
RcppExport SEXP _ply_cpp_enrich_batch(SEXP fensSEXP, SEXP uci_movesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type fens(fensSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type uci_moves(uci_movesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_enrich_batch(fens, uci_moves));
    return rcpp_result_gen;
END_RCPP
}
// cpp_san_to_uci
std::string cpp_san_to_uci(List state, std::string san);
RcppExport SEXP _ply_cpp_san_to_uci(SEXP stateSEXP, SEXP sanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type state(stateSEXP);
    Rcpp::traits::input_parameter< std::string >::type san(sanSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_san_to_uci(state, san));
    return rcpp_result_gen;
END_RCPP
}
// cpp_replay_game
DataFrame cpp_replay_game(StringVector san_moves);
RcppExport SEXP _ply_cpp_replay_game(SEXP san_movesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringVector >::type san_moves(san_movesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_replay_game(san_moves));
    return rcpp_result_gen;
END_RCPP
}
// cpp_replay_games_batch
DataFrame cpp_replay_games_batch(IntegerVector game_ids, StringVector san_moves, IntegerVector game_starts);
RcppExport SEXP _ply_cpp_replay_games_batch(SEXP game_idsSEXP, SEXP san_movesSEXP, SEXP game_startsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type game_ids(game_idsSEXP);
    Rcpp::traits::input_parameter< StringVector >::type san_moves(san_movesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type game_starts(game_startsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_replay_games_batch(game_ids, san_moves, game_starts));
    return rcpp_result_gen;
END_RCPP
}
// cpp_replay_pgn_file
DataFrame cpp_replay_pgn_file(std::string path);
RcppExport SEXP _ply_cpp_replay_pgn_file(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_replay_pgn_file(path));
    return rcpp_result_gen;
END_RCPP
}
// cpp_create_game
int cpp_create_game(std::string creator, int settlement_mode, double ply_time_limit, double initial_time, double increment, int time_mode, bool as_black);
RcppExport SEXP _ply_cpp_create_game(SEXP creatorSEXP, SEXP settlement_modeSEXP, SEXP ply_time_limitSEXP, SEXP initial_timeSEXP, SEXP incrementSEXP, SEXP time_modeSEXP, SEXP as_blackSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type creator(creatorSEXP);
    Rcpp::traits::input_parameter< int >::type settlement_mode(settlement_modeSEXP);
    Rcpp::traits::input_parameter< double >::type ply_time_limit(ply_time_limitSEXP);
    Rcpp::traits::input_parameter< double >::type initial_time(initial_timeSEXP);
    Rcpp::traits::input_parameter< double >::type increment(incrementSEXP);
    Rcpp::traits::input_parameter< int >::type time_mode(time_modeSEXP);
    Rcpp::traits::input_parameter< bool >::type as_black(as_blackSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_create_game(creator, settlement_mode, ply_time_limit, initial_time, increment, time_mode, as_black));
    return rcpp_result_gen;
END_RCPP
}
// cpp_create_game_from_fen
int cpp_create_game_from_fen(std::string creator, std::string fen, int settlement_mode, double ply_time_limit, double initial_time, double increment, int time_mode, bool as_black);
RcppExport SEXP _ply_cpp_create_game_from_fen(SEXP creatorSEXP, SEXP fenSEXP, SEXP settlement_modeSEXP, SEXP ply_time_limitSEXP, SEXP initial_timeSEXP, SEXP incrementSEXP, SEXP time_modeSEXP, SEXP as_blackSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type creator(creatorSEXP);
    Rcpp::traits::input_parameter< std::string >::type fen(fenSEXP);
    Rcpp::traits::input_parameter< int >::type settlement_mode(settlement_modeSEXP);
    Rcpp::traits::input_parameter< double >::type ply_time_limit(ply_time_limitSEXP);
    Rcpp::traits::input_parameter< double >::type initial_time(initial_timeSEXP);
    Rcpp::traits::input_parameter< double >::type increment(incrementSEXP);
    Rcpp::traits::input_parameter< int >::type time_mode(time_modeSEXP);
    Rcpp::traits::input_parameter< bool >::type as_black(as_blackSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_create_game_from_fen(creator, fen, settlement_mode, ply_time_limit, initial_time, increment, time_mode, as_black));
    return rcpp_result_gen;
END_RCPP
}
// cpp_join_game
bool cpp_join_game(int game_id, std::string player);
RcppExport SEXP _ply_cpp_join_game(SEXP game_idSEXP, SEXP playerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type game_id(game_idSEXP);
    Rcpp::traits::input_parameter< std::string >::type player(playerSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_join_game(game_id, player));
    return rcpp_result_gen;
END_RCPP
}
// cpp_make_ply
bool cpp_make_ply(int game_id, std::string player, int ply, bool settle);
RcppExport SEXP _ply_cpp_make_ply(SEXP game_idSEXP, SEXP playerSEXP, SEXP plySEXP, SEXP settleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type game_id(game_idSEXP);
    Rcpp::traits::input_parameter< std::string >::type player(playerSEXP);
    Rcpp::traits::input_parameter< int >::type ply(plySEXP);
    Rcpp::traits::input_parameter< bool >::type settle(settleSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_make_ply(game_id, player, ply, settle));
    return rcpp_result_gen;
END_RCPP
}
// cpp_make_ply_uci
bool cpp_make_ply_uci(int game_id, std::string player, std::string uci, bool settle);
RcppExport SEXP _ply_cpp_make_ply_uci(SEXP game_idSEXP, SEXP playerSEXP, SEXP uciSEXP, SEXP settleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type game_id(game_idSEXP);
    Rcpp::traits::input_parameter< std::string >::type player(playerSEXP);
    Rcpp::traits::input_parameter< std::string >::type uci(uciSEXP);
    Rcpp::traits::input_parameter< bool >::type settle(settleSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_make_ply_uci(game_id, player, uci, settle));
    return rcpp_result_gen;
END_RCPP
}
// cpp_resign
bool cpp_resign(int game_id, std::string player);
RcppExport SEXP _ply_cpp_resign(SEXP game_idSEXP, SEXP playerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type game_id(game_idSEXP);
    Rcpp::traits::input_parameter< std::string >::type player(playerSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_resign(game_id, player));
    return rcpp_result_gen;
END_RCPP
}
// cpp_offer_draw
bool cpp_offer_draw(int game_id, std::string player);
RcppExport SEXP _ply_cpp_offer_draw(SEXP game_idSEXP, SEXP playerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type game_id(game_idSEXP);
    Rcpp::traits::input_parameter< std::string >::type player(playerSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_offer_draw(game_id, player));
    return rcpp_result_gen;
END_RCPP
}
// cpp_accept_draw
bool cpp_accept_draw(int game_id, std::string player);
RcppExport SEXP _ply_cpp_accept_draw(SEXP game_idSEXP, SEXP playerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type game_id(game_idSEXP);
    Rcpp::traits::input_parameter< std::string >::type player(playerSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_accept_draw(game_id, player));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cancel_game
bool cpp_cancel_game(int game_id, std::string player);
RcppExport SEXP _ply_cpp_cancel_game(SEXP game_idSEXP, SEXP playerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type game_id(game_idSEXP);
    Rcpp::traits::input_parameter< std::string >::type player(playerSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cancel_game(game_id, player));
    return rcpp_result_gen;
END_RCPP
}
// cpp_get_game_info
List cpp_get_game_info(int game_id);
RcppExport SEXP _ply_cpp_get_game_info(SEXP game_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type game_id(game_idSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_get_game_info(game_id));
    return rcpp_result_gen;
END_RCPP
}
// cpp_get_fen
std::string cpp_get_fen(int game_id);
RcppExport SEXP _ply_cpp_get_fen(SEXP game_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type game_id(game_idSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_get_fen(game_id));
    return rcpp_result_gen;
END_RCPP
}
// cpp_get_ply_history
CharacterVector cpp_get_ply_history(int game_id);
RcppExport SEXP _ply_cpp_get_ply_history(SEXP game_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type game_id(game_idSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_get_ply_history(game_id));
    return rcpp_result_gen;
END_RCPP
}
// cpp_reset_registry
void cpp_reset_registry();
RcppExport SEXP _ply_cpp_reset_registry() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    cpp_reset_registry();
    return R_NilValue;
END_RCPP
}
// cpp_game_count
int cpp_game_count();
RcppExport SEXP _ply_cpp_game_count() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_game_count());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ply_cpp_xp_init_game", (DL_FUNC) &_ply_cpp_xp_init_game, 0},
    {"_ply_cpp_xp_parse_fen", (DL_FUNC) &_ply_cpp_xp_parse_fen, 1},
    {"_ply_cpp_xp_state_to_fen", (DL_FUNC) &_ply_cpp_xp_state_to_fen, 1},
    {"_ply_cpp_xp_in_check", (DL_FUNC) &_ply_cpp_xp_in_check, 2},
    {"_ply_cpp_xp_is_legal_ply", (DL_FUNC) &_ply_cpp_xp_is_legal_ply, 2},
    {"_ply_cpp_xp_apply_ply", (DL_FUNC) &_ply_cpp_xp_apply_ply, 2},
    {"_ply_cpp_xp_generate_legal_moves", (DL_FUNC) &_ply_cpp_xp_generate_legal_moves, 1},
    {"_ply_cpp_xp_count_legal_moves", (DL_FUNC) &_ply_cpp_xp_count_legal_moves, 1},
    {"_ply_cpp_xp_is_insufficient_material", (DL_FUNC) &_ply_cpp_xp_is_insufficient_material, 1},
    {"_ply_cpp_xp_validate_position", (DL_FUNC) &_ply_cpp_xp_validate_position, 1},
    {"_ply_cpp_xp_position_hash", (DL_FUNC) &_ply_cpp_xp_position_hash, 1},
    {"_ply_cpp_xp_perft", (DL_FUNC) &_ply_cpp_xp_perft, 2},
    {"_ply_cpp_init_game", (DL_FUNC) &_ply_cpp_init_game, 0},
    {"_ply_cpp_parse_fen", (DL_FUNC) &_ply_cpp_parse_fen, 1},
    {"_ply_cpp_state_to_fen", (DL_FUNC) &_ply_cpp_state_to_fen, 1},
    {"_ply_cpp_in_check", (DL_FUNC) &_ply_cpp_in_check, 2},
    {"_ply_cpp_is_legal_ply", (DL_FUNC) &_ply_cpp_is_legal_ply, 2},
    {"_ply_cpp_apply_ply", (DL_FUNC) &_ply_cpp_apply_ply, 2},
    {"_ply_cpp_generate_legal_moves", (DL_FUNC) &_ply_cpp_generate_legal_moves, 1},
    {"_ply_cpp_has_any_legal_ply_with_check", (DL_FUNC) &_ply_cpp_has_any_legal_ply_with_check, 1},
    {"_ply_cpp_is_insufficient_material", (DL_FUNC) &_ply_cpp_is_insufficient_material, 1},
    {"_ply_cpp_validate_position", (DL_FUNC) &_ply_cpp_validate_position, 1},
    {"_ply_cpp_uci_to_ply", (DL_FUNC) &_ply_cpp_uci_to_ply, 2},
    {"_ply_cpp_ply_to_uci", (DL_FUNC) &_ply_cpp_ply_to_uci, 1},
    {"_ply_cpp_position_hash", (DL_FUNC) &_ply_cpp_position_hash, 1},
    {"_ply_cpp_enrich_batch", (DL_FUNC) &_ply_cpp_enrich_batch, 2},
    {"_ply_cpp_san_to_uci", (DL_FUNC) &_ply_cpp_san_to_uci, 2},
    {"_ply_cpp_replay_game", (DL_FUNC) &_ply_cpp_replay_game, 1},
    {"_ply_cpp_replay_games_batch", (DL_FUNC) &_ply_cpp_replay_games_batch, 3},
    {"_ply_cpp_replay_pgn_file", (DL_FUNC) &_ply_cpp_replay_pgn_file, 1},
    {"_ply_cpp_create_game", (DL_FUNC) &_ply_cpp_create_game, 7},
    {"_ply_cpp_create_game_from_fen", (DL_FUNC) &_ply_cpp_create_game_from_fen, 8},
    {"_ply_cpp_join_game", (DL_FUNC) &_ply_cpp_join_game, 2},
    {"_ply_cpp_make_ply", (DL_FUNC) &_ply_cpp_make_ply, 4},
    {"_ply_cpp_make_ply_uci", (DL_FUNC) &_ply_cpp_make_ply_uci, 4},
    {"_ply_cpp_resign", (DL_FUNC) &_ply_cpp_resign, 2},
    {"_ply_cpp_offer_draw", (DL_FUNC) &_ply_cpp_offer_draw, 2},
    {"_ply_cpp_accept_draw", (DL_FUNC) &_ply_cpp_accept_draw, 2},
    {"_ply_cpp_cancel_game", (DL_FUNC) &_ply_cpp_cancel_game, 2},
    {"_ply_cpp_get_game_info", (DL_FUNC) &_ply_cpp_get_game_info, 1},
    {"_ply_cpp_get_fen", (DL_FUNC) &_ply_cpp_get_fen, 1},
    {"_ply_cpp_get_ply_history", (DL_FUNC) &_ply_cpp_get_ply_history, 1},
    {"_ply_cpp_reset_registry", (DL_FUNC) &_ply_cpp_reset_registry, 0},
    {"_ply_cpp_game_count", (DL_FUNC) &_ply_cpp_game_count, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_ply(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
