# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_xp_init_game <- function() {
    .Call(`_ply_cpp_xp_init_game`)
}

cpp_xp_parse_fen <- function(fen) {
    .Call(`_ply_cpp_xp_parse_fen`, fen)
}

cpp_xp_state_to_fen <- function(state) {
    .Call(`_ply_cpp_xp_state_to_fen`, state)
}

cpp_xp_in_check <- function(state, color) {
    .Call(`_ply_cpp_xp_in_check`, state, color)
}

cpp_xp_is_legal_ply <- function(state, ply) {
    .Call(`_ply_cpp_xp_is_legal_ply`, state, ply)
}

cpp_xp_apply_ply <- function(state, ply) {
    .Call(`_ply_cpp_xp_apply_ply`, state, ply)
}

cpp_xp_generate_legal_moves <- function(state) {
    .Call(`_ply_cpp_xp_generate_legal_moves`, state)
}

cpp_xp_count_legal_moves <- function(state) {
    .Call(`_ply_cpp_xp_count_legal_moves`, state)
}

cpp_xp_is_insufficient_material <- function(state) {
    .Call(`_ply_cpp_xp_is_insufficient_material`, state)
}

cpp_xp_validate_position <- function(state) {
    .Call(`_ply_cpp_xp_validate_position`, state)
}

cpp_xp_position_hash <- function(state) {
    .Call(`_ply_cpp_xp_position_hash`, state)
}

cpp_xp_perft <- function(fen, depth) {
    .Call(`_ply_cpp_xp_perft`, fen, depth)
}

cpp_init_game <- function() {
    .Call(`_ply_cpp_init_game`)
}

cpp_parse_fen <- function(fen) {
    .Call(`_ply_cpp_parse_fen`, fen)
}

cpp_state_to_fen <- function(state) {
    .Call(`_ply_cpp_state_to_fen`, state)
}

cpp_in_check <- function(state, color) {
    .Call(`_ply_cpp_in_check`, state, color)
}

cpp_is_legal_ply <- function(state, ply) {
    .Call(`_ply_cpp_is_legal_ply`, state, ply)
}

cpp_apply_ply <- function(state, ply) {
    .Call(`_ply_cpp_apply_ply`, state, ply)
}

cpp_generate_legal_moves <- function(state) {
    .Call(`_ply_cpp_generate_legal_moves`, state)
}

cpp_has_any_legal_ply_with_check <- function(state) {
    .Call(`_ply_cpp_has_any_legal_ply_with_check`, state)
}

cpp_is_insufficient_material <- function(state) {
    .Call(`_ply_cpp_is_insufficient_material`, state)
}

cpp_validate_position <- function(state) {
    .Call(`_ply_cpp_validate_position`, state)
}

cpp_uci_to_ply <- function(state, uci) {
    .Call(`_ply_cpp_uci_to_ply`, state, uci)
}

cpp_ply_to_uci <- function(ply) {
    .Call(`_ply_cpp_ply_to_uci`, ply)
}

cpp_position_hash <- function(state) {
    .Call(`_ply_cpp_position_hash`, state)
}

cpp_enrich_batch <- function(fens, uci_moves) {
    .Call(`_ply_cpp_enrich_batch`, fens, uci_moves)
}

cpp_san_to_uci <- function(state, san) {
    .Call(`_ply_cpp_san_to_uci`, state, san)
}

cpp_replay_game <- function(san_moves) {
    .Call(`_ply_cpp_replay_game`, san_moves)
}

cpp_replay_games_batch <- function(game_ids, san_moves, game_starts) {
    .Call(`_ply_cpp_replay_games_batch`, game_ids, san_moves, game_starts)
}

cpp_replay_pgn_file <- function(path) {
    .Call(`_ply_cpp_replay_pgn_file`, path)
}

cpp_create_game <- function(creator, settlement_mode, ply_time_limit, initial_time = 0, increment = 0, time_mode = 0L, as_black = FALSE) {
    .Call(`_ply_cpp_create_game`, creator, settlement_mode, ply_time_limit, initial_time, increment, time_mode, as_black)
}

cpp_create_game_from_fen <- function(creator, fen, settlement_mode, ply_time_limit, initial_time = 0, increment = 0, time_mode = 0L, as_black = FALSE) {
    .Call(`_ply_cpp_create_game_from_fen`, creator, fen, settlement_mode, ply_time_limit, initial_time, increment, time_mode, as_black)
}

cpp_join_game <- function(game_id, player) {
    .Call(`_ply_cpp_join_game`, game_id, player)
}

cpp_make_ply <- function(game_id, player, ply, settle = FALSE) {
    .Call(`_ply_cpp_make_ply`, game_id, player, ply, settle)
}

cpp_make_ply_uci <- function(game_id, player, uci, settle = FALSE) {
    .Call(`_ply_cpp_make_ply_uci`, game_id, player, uci, settle)
}

cpp_resign <- function(game_id, player) {
    .Call(`_ply_cpp_resign`, game_id, player)
}

cpp_offer_draw <- function(game_id, player) {
    .Call(`_ply_cpp_offer_draw`, game_id, player)
}

cpp_accept_draw <- function(game_id, player) {
    .Call(`_ply_cpp_accept_draw`, game_id, player)
}

cpp_cancel_game <- function(game_id, player) {
    .Call(`_ply_cpp_cancel_game`, game_id, player)
}

cpp_get_game_info <- function(game_id) {
    .Call(`_ply_cpp_get_game_info`, game_id)
}

cpp_get_fen <- function(game_id) {
    .Call(`_ply_cpp_get_fen`, game_id)
}

cpp_get_ply_history <- function(game_id) {
    .Call(`_ply_cpp_get_ply_history`, game_id)
}

cpp_reset_registry <- function() {
    invisible(.Call(`_ply_cpp_reset_registry`))
}

cpp_game_count <- function() {
    .Call(`_ply_cpp_game_count`)
}

